FORMAT: 1A

# Group Login
## ログイン [/api/v1/login]
### ログイン [POST]
ログイン時のレスポンスとして受け取るデータのうち、manualsは全件取得する。
ただしrootTreeはnullの状態とする。
favorites, likes はマニュアルidを保持する。(マニュアルのプロパティー内の favorites, likes はユーザーidを保持する。)

+ Request  (application/json)

        {
            "id": "user1234",
            "password": "pass1234"
        },

+ Response 200 (application/json)

        {
            "user": {
                "id": "user1234",
                "lastName": "テスト",
                "firstName": "太郎",
                "userManagement": {
                    "canCreate": true,
                    "canEdit": true,
                    "canDelete": true
                },
                "groupManagement": {
                    "canCreate": true,
                    "canEdit": true,
                    "canDelete": true
                },
                "isOperationManager": true
            },
            "users": [
                {
                    "id": "user1234",
                    "lastName": "テスト",
                    "firstName": "太郎",
                    "userManagement": {
                        "canCreate": true,
                        "canEdit": true,
                        "canDelete": true
                    },
                    "groupManagement": {
                        "canCreate": true,
                        "canEdit": true,
                        "canDelete": true
                    },
                    "isOperationManager": true
                },
                {
                    "id": "user2222",
                    "lastName": "テスト",
                    "firstName": "太郎2",
                    "userManagement": {
                        "canCreate": true,
                        "canEdit": true,
                        "canDelete": true
                    },
                    "groupManagement": {
                        "canCreate": true,
                        "canEdit": true,
                        "canDelete": true
                    },
                    "isOperationManager": true
                },
                {
                    "id": "user3333",
                    "lastName": "テスト",
                    "firstName": "太郎3",
                    "userManagement": {
                        "canCreate": true,
                        "canEdit": true,
                        "canDelete": true
                    },
                    "groupManagement": {
                        "canCreate": true,
                        "canEdit": true,
                        "canDelete": true
                    },
                    "isOperationManager": true
                }
            ],
            "categories": [
                {
                    "id": "1",
                    "name": "未分類カテゴリー",
                },
                {
                    "id": "2",
                    "name": "営業",
                },
                {
                    "id": "3",
                    "name": "ソフトウェア",
                },
                {
                    "id": "4",
                    "name": "経理",
                },
                {
                    "id": "5",
                    "name": "法務",
                },
                {
                    "id": "6",
                    "name": "教育",
                },
            ],
            "manuals": [
                {
                    "id": "1",
                    "label": "営業マニュアル",
                    "ownerId": "user1234",
                    "collaboratorIds": ["user2222"],
                    "category": "2",
                    "isPublic": true,
                    "visible": true,
                    "favorites": [],
                    "likes": [],
                    "rootTree": null,
                },
                {
                    "id": "2",
                    "label": "ソフトウェアマニュアル",
                    "ownerId": "user1234",
                    "collaboratorIds": ["user2222"],
                    "category": "3",
                    "isPublic": true,
                    "visible": true,
                    "favorites": [],
                    "likes": [],
                    "rootTree": null,
                }
            ],
            "favorites": [],
            "likes": [],
            "memos": [
                {
                    "id": "4",
                    "label": "マニュアル4のメモ",
                    "input": "",
                    "output": "",
                    "preConditions": "",
                    "postConditions": "",
                    "workerInCharge": "",
                    "remarks": "",
                    "necessaryTools": "",
                    "exceptions": "",
                    "imageName": "",
                    "imageBlob": "",
                    "point": {
                        "x": 200,
                        "y": 300
                    },
                    "children": []
                }
            ],
        }

### ログアウト [DELETE]
+ Response 200

# Group Manual
## マニュアル [/api/v1/manual/{id}]
DB未保存のデータはidを"tmp:~"で始めるルールとする。
おそらく親となるレコードのIDを子が持つDB設計になると思うが、
レコードの削除はrootとなるマニュアルデータ以外は明示的なAPIを持たないため、
編集時に削除されたデータがあるかどうかをチェックし、
あれば該当レコードを削除するロジックをサーバーサイドで組む必要がある。

### マニュアル取得API [GET]
リクエストパラメーターでmanualIdを渡し、rootTree以下のNodeを返す。

+ Parameters
    + id: 123 (string, required) - manualId

+ Response 200 (application/json)

        {
            "id": "1",
            "label": "営業マニュアル",
            "ownerId": "user1234",
            "collaboratorIds": ["user2222"],
            "category": "2",
            "isPublic": true,
            "visible": true,
            "favorites": [],
            "likes": [],
            "rootTree": {
                "id": "1231",
                "label": "マニュアル１",
                "type": "task",
                "input": "",
                "output": "",
                "preConditions": "",
                "postConditions": "",
                "workerInCharge": "",
                "remarks": "",
                "necessaryTools": "",
                "exceptions": "",
                "imageName": "",
                "imageBlob": "",
                "children": [
                    {
                        "id": "1232",
                        "label": "マニュアル１−１",
                        "type": "task",
                        "input": "",
                        "output": "",
                        "preConditions": "",
                        "postConditions": "",
                        "workerInCharge": "",
                        "remarks": "",
                        "necessaryTools": "",
                        "exceptions": "",
                        "imageName": "",
                        "imageBlob": "",
                        "children": []
                    }
                ]
            }
        }


### マニュアル作成API [POST]

+ Request  (application/json)

        {
            "id": "tmp:1",
            "label": "マニュアル1",
            "ownerId": "user1234",
            "collaboratorIds": [],
            "category": "3",
            "isPublic": true,
            "visible": true,
            "favorites": [],
            "likes": [],
            "rootTree": {
                "id": "tmp:12",
                "label": "",
                "type": "task",
                "input": "",
                "output": "",
                "preConditions": "",
                "postConditions": "",
                "workerInCharge": "",
                "remarks": "",
                "necessaryTools": "",
                "exceptions": "",
                "imageName": "",
                "imageBlob": "",
                "children": []
            }
        }

+ Response 200 (application/json)

        {
            "id": "1",
            "label": "マニュアル1",
            "ownerId": "user1234",
            "collaboratorIds": [],
            "category": "3",
            "isPublic": true,
            "visible": true,
            "favorites": [],
            "likes": [],
            "rootTree": {
                "id": "12",
                "label": "",
                "type": "task",
                "input": "",
                "output": "",
                "preConditions": "",
                "postConditions": "",
                "workerInCharge": "",
                "remarks": "",
                "necessaryTools": "",
                "exceptions": "",
                "imageName": "",
                "imageBlob": "",
                "children": []
            }
        }

### マニュアル編集API [PUT]

+ Parameters
    + id: 123 (string, required) - manualId

+ Request  (application/json)

        {
            "id": "1",
            "label": "マニュアル1",
            "ownerId": "user1234",
            "collaboratorIds": [],
            "category": "3",
            "isPublic": true,
            "visible": true,
            "favorites": [],
            "likes": [],
            "rootTree": {
                "id": "12",
                "label": "マニュアル１−１",
                "type": "task",
                "input": "",
                "output": "",
                "preConditions": "",
                "postConditions": "",
                "workerInCharge": "",
                "remarks": "",
                "necessaryTools": "",
                "exceptions": "",
                "imageName": "",
                "imageBlob": "",
                "children": [
                    "id": "tmp:12",
                    "label": "マニュアル１−１",
                    "type": "task",
                    "input": "",
                    "output": "",
                    "preConditions": "",
                    "postConditions": "",
                    "workerInCharge": "",
                    "remarks": "",
                    "necessaryTools": "",
                    "exceptions": "",
                    "imageName": "",
                    "imageBlob": "",
                    "children": []
                ]
            }
        }

+ Response 200 (application/json)

        {
            "id": "1",
            "label": "マニュアル1",
            "ownerId": "user1234",
            "collaboratorIds": [],
            "category": "3",
            "isPublic": true,
            "visible": true,
            "favorites": [],
            "likes": [],
            "rootTree": {
                "id": "12",
                "label": "マニュアル１−１",
                "type": "task",
                "input": "",
                "output": "",
                "preConditions": "",
                "postConditions": "",
                "workerInCharge": "",
                "remarks": "",
                "necessaryTools": "",
                "exceptions": "",
                "imageName": "",
                "imageBlob": "",
                "children": [
                    "id": "123",
                    "label": "マニュアル１−１",
                    "type": "task",
                    "input": "",
                    "output": "",
                    "preConditions": "",
                    "postConditions": "",
                    "workerInCharge": "",
                    "remarks": "",
                    "necessaryTools": "",
                    "exceptions": "",
                    "imageName": "",
                    "imageBlob": "",
                    "children": []
                ]
            }
        }

### マニュアル削除API [DELETE]
+ Parameters
    + id: 123 (string, required) - manualId

+ Response 200 (application/json)

# Group Favorite
## お気に入り [/api/v1/favorites/{manualId}/{userId}]
### お気に入り登録 [POST]

+ Parameters
    + manualId: 123 (string, required) - manualId
    + userId: user1234 (string, required) - userId

+ Response 200 (application/json)

### お気に入り編集 [PUT]

+ Parameters
    + manualId: 123 (string, required) - manualId
    + userId: user1234 (string, required) - userId

+ Request  (application/json)

        {
            "follow": true
        }

+ Response 200 (application/json)

### お気に入り解除 [DELETE]

+ Parameters
    + manualId: 123 (string, required) - manualId
    + userId: user1234 (string, required) - userId

+ Response 200 (application/json)

# Group Like
## いいね [/api/v1/likes/{id}]
### いいね登録 [POST]

+ Parameters
    + id: 123 (string, required) - manualId

+ Response 200 (application/json)

### いいね解除 [DELETE]

+ Parameters
    + id: 123 (string, required) - manualId

+ Response 200 (application/json)